version: "3.9"

services:
  nuxt:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      HOST: "0.0.0.0"
      CHOKIDAR_USEPOLLING: "1"
    volumes:
      - .:/app
      - /app/node_modules

  ws:
    build: .
    command: npm run server
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      NODE_ENV: "development"
    volumes:
      - .:/app
      - /app/node_modules
