# Build Nuxt
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ENV NITRO_PRESET=node
RUN npm run build

# Runtime Nuxt
FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
# Nuxt/Nitro écoutera sur ce port dans le conteneur
ENV NITRO_HOST=0.0.0.0
ENV NITRO_PORT=3000
EXPOSE 3000
COPY --from=builder /app/.output ./.output
CMD ["node", ".output/server/index.mjs"]
